openapi: 3.1.0
info:
  title: Supabase Simple Search API
  description: API to search for similar articles based on a query string.
  version: 1.0.0
  termsOfService: https://example.com/terms/
  contact:
    name: API Support
    url: https://example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  privacyPolicy: https://example.com/privacy-policy
servers:
  - url: https://jefqrizenjvzaumvplgl.supabase.co/functions/v1
    description: Main production server
paths:
  /simple-search:
    post:
      operationId: searchSimilarArticles
      summary: Search for similar articles.
      description: Submit a query to search for articles that are similar to the provided query string.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: "Ring CX phone services"
                  description: The search query string to find similar articles.
      responses:
        '200':
          description: A list of similar articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: Title of the article
                    url:
                      type: string
                      description: URL of the article
                    summary:
                      type: string
                      description: Summary of the article
        '400':
          description: Bad request, likely due to missing or invalid query string
        '500':
          description: Internal server error
